// Sample data with Indian names for business matchmaking platform

export const indianNames = {
  firstNames: [
    "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Reyansh", "Ayaan", "Aarush", "Atharv", "Advik",
    "Ishaan", "Kabir", "Dhruv", "Shaurya", "Ritvik", "Aarush", "Anay", "Daksh", "Abeer", "Aaryan",
    "Aadhya", "Anaya", "Pari", "Diya", "Ira", "Anika", "Aarohi", "Meera", "Sara", "Anvi",
    "Prisha", "Riya", "Myra", "Kavya", "Naira", "Jiya", "Siya", "Vanya", "Tara", "Zara",
    "Rohit", "Amit", "Rajesh", "Suresh", "Vikram", "Deepak", "Manoj", "Sanjay", "Ajay", "Ravi",
    "Priya", "Anjali", "Kavita", "Sunita", "Rekha", "Geeta", "Meena", "Neeta", "Seema", "Reena"
  ],
  lastNames: [
    "Sharma", "Patel", "Kumar", "Singh", "Gupta", "Verma", "Jain", "Agarwal", "Pandey", "Thakur",
    "Yadav", "Mishra", "Tiwari", "Das", "Choudhary", "Khan", "Shah", "Mehta", "Patil", "Reddy",
    "Nair", "Menon", "Pillai", "Iyer", "Rao", "Joshi", "Bhat", "Chowdhury", "Sinha", "Chakraborty"
  ]
};

export const indianCompanies = [
  "TechNova Solutions", "Bharat FinTech", "Hindustan AgriTech", "DesiHealth Systems", "Swadeshi Commerce",
  "Arya Logistics", "Vedanta Energy", "Prakashan Media", "Sanskriti Education", "Dharma Analytics",
  "Mantra Consulting", "Karma Robotics", "Nirvana Wellness", "Shakti Power", "Bhakti Foods",
  "Jnana AI", "Prema Healthcare", "Satya Security", "Dharma Digital", "Moksha Mobile"
];

export const businessCategories = [
  "Technology", "Healthcare", "Finance", "Agriculture", "E-commerce", "Education", "Energy",
  "Food & Beverage", "Logistics", "Real Estate", "Travel", "Entertainment", "Automotive",
  "Fashion", "Sports", "Telecommunications", "Manufacturing", "Consulting", "Media", "Retail"
];

export const sampleUsers = [
  // Investors (15 users)
  {
    email: "arjun.sharma@email.com",
    name: "Arjun Sharma",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Sharma Ventures",
    industry: "Technology",
    experience: "15 years in tech investments",
    investmentRange: { min: 100000, max: 1000000 },
    preferredIndustries: ["Technology", "Healthcare", "Finance"],
    riskTolerance: "medium" as const,
    bio: "Experienced tech investor with a focus on early-stage startups in India",
    location: "Mumbai, Maharashtra",
    website: "https://sharmaventures.com",
    socialLinks: { linkedin: "https://linkedin.com/in/arjunsharma", twitter: "https://twitter.com/arjunsharma" }
  },
  {
    email: "priya.patel@email.com",
    name: "Priya Patel",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Patel Capital",
    industry: "Healthcare",
    experience: "12 years in healthcare investments",
    investmentRange: { min: 50000, max: 500000 },
    preferredIndustries: ["Healthcare", "Biotech", "Medical Devices"],
    riskTolerance: "low" as const,
    bio: "Healthcare-focused investor passionate about improving medical access in India",
    location: "Ahmedabad, Gujarat",
    website: "https://patelcapital.in"
  },
  {
    email: "vikram.verma@email.com",
    name: "Vikram Verma",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Verma Holdings",
    industry: "Finance",
    experience: "20 years in financial services",
    investmentRange: { min: 200000, max: 2000000 },
    preferredIndustries: ["Finance", "Technology", "Real Estate"],
    riskTolerance: "high" as const,
    bio: "Serial entrepreneur and investor with multiple successful exits",
    location: "Bangalore, Karnataka"
  },
  {
    email: "anaya.gupta@email.com",
    name: "Anaya Gupta",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Gupta Family Office",
    industry: "E-commerce",
    experience: "8 years in retail and e-commerce",
    investmentRange: { min: 75000, max: 750000 },
    preferredIndustries: ["E-commerce", "Retail", "Consumer Goods"],
    riskTolerance: "medium" as const,
    bio: "Next-generation investor focusing on consumer technology",
    location: "Delhi, India"
  },
  {
    email: "rohit.singh@email.com",
    name: "Rohit Singh",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Singh Investments",
    industry: "Agriculture",
    experience: "10 years in agribusiness",
    investmentRange: { min: 50000, max: 400000 },
    preferredIndustries: ["Agriculture", "Food & Beverage", "Sustainability"],
    riskTolerance: "low" as const,
    bio: "Agri-tech investor working to modernize Indian agriculture",
    location: "Punjab, India"
  },
  {
    email: "kavita.jain@email.com",
    name: "Kavita Jain",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Jain Ventures",
    industry: "Education",
    experience: "14 years in education technology",
    investmentRange: { min: 100000, max: 800000 },
    preferredIndustries: ["Education", "Technology", "Media"],
    riskTolerance: "medium" as const,
    bio: "Education reformer investing in innovative learning solutions",
    location: "Jaipur, Rajasthan"
  },
  {
    email: "deepak.reddy@email.com",
    name: "Deepak Reddy",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Reddy Capital Partners",
    industry: "Energy",
    experience: "16 years in energy sector",
    investmentRange: { min: 150000, max: 1500000 },
    preferredIndustries: ["Energy", "Sustainability", "Manufacturing"],
    riskTolerance: "high" as const,
    bio: "Clean energy advocate investing in sustainable technologies",
    location: "Hyderabad, Telangana"
  },
  {
    email: "meera.menon@email.com",
    name: "Meera Menon",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Menon Investments",
    industry: "Entertainment",
    experience: "11 years in media and entertainment",
    investmentRange: { min: 80000, max: 600000 },
    preferredIndustries: ["Entertainment", "Media", "Sports"],
    riskTolerance: "medium" as const,
    bio: "Entertainment industry veteran investing in digital content",
    location: "Mumbai, Maharashtra"
  },
  {
    email: "amit.pandey@email.com",
    name: "Amit Pandey",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Pandey Group",
    industry: "Logistics",
    experience: "13 years in supply chain",
    investmentRange: { min: 120000, max: 900000 },
    preferredIndustries: ["Logistics", "Technology", "E-commerce"],
    riskTolerance: "medium" as const,
    bio: "Logistics expert investing in supply chain innovations",
    location: "Pune, Maharashtra"
  },
  {
    email: "sunita.choudhary@email.com",
    name: "Sunita Choudhary",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Choudhary Family Trust",
    industry: "Fashion",
    experience: "9 years in fashion retail",
    investmentRange: { min: 60000, max: 500000 },
    preferredIndustries: ["Fashion", "Retail", "Consumer Goods"],
    riskTolerance: "low" as const,
    bio: "Fashion entrepreneur supporting emerging designers",
    location: "Surat, Gujarat"
  },
  {
    email: "ravi.tiwari@email.com",
    name: "Ravi Tiwari",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Tiwari Capital",
    industry: "Real Estate",
    experience: "18 years in real estate",
    investmentRange: { min: 200000, max: 2000000 },
    preferredIndustries: ["Real Estate", "Construction", "Technology"],
    riskTolerance: "high" as const,
    bio: "Real estate developer investing in prop-tech solutions",
    location: "Gurgaon, Haryana"
  },
  {
    email: "geeta.nair@email.com",
    name: "Geeta Nair",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Nair Investments",
    industry: "Travel",
    experience: "12 years in hospitality",
    investmentRange: { min: 90000, max: 700000 },
    preferredIndustries: ["Travel", "Hospitality", "Technology"],
    riskTolerance: "medium" as const,
    bio: "Hospitality professional investing in travel technology",
    location: "Kochi, Kerala"
  },
  {
    email: "manoj.das@email.com",
    name: "Manoj Das",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Das Ventures",
    industry: "Automotive",
    experience: "15 years in automotive",
    investmentRange: { min: 110000, max: 850000 },
    preferredIndustries: ["Automotive", "Manufacturing", "Technology"],
    riskTolerance: "medium" as const,
    bio: "Automotive engineer investing in mobility solutions",
    location: "Chennai, Tamil Nadu"
  },
  {
    email: "rekha.bhat@email.com",
    name: "Rekha Bhat",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Bhat Family Office",
    industry: "Telecommunications",
    experience: "10 years in telecom",
    investmentRange: { min: 130000, max: 1000000 },
    preferredIndustries: ["Telecommunications", "Technology", "Media"],
    riskTolerance: "high" as const,
    bio: "Telecom executive investing in communication technologies",
    location: "Bangalore, Karnataka"
  },
  {
    email: "sanjay.joshi@email.com",
    name: "Sanjay Joshi",
    userType: "investor" as const,
    isVerified: true,
    companyName: "Joshi Capital",
    industry: "Consulting",
    experience: "17 years in management consulting",
    investmentRange: { min: 95000, max: 650000 },
    preferredIndustries: ["Consulting", "Technology", "Finance"],
    riskTolerance: "medium" as const,
    bio: "Management consultant investing in business services",
    location: "Mumbai, Maharashtra"
  },

  // Creators (15 users)
  {
    email: "aarav.kumar@email.com",
    name: "Aarav Kumar",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Kumar Tech",
    industry: "Technology",
    experience: "5 years in software development",
    bio: "Full-stack developer passionate about AI solutions",
    location: "Bangalore, Karnataka"
  },
  {
    email: "diya.verma@email.com",
    name: "Diya Verma",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Diya HealthTech",
    industry: "Healthcare",
    experience: "7 years in healthcare IT",
    bio: "Healthcare innovator developing telemedicine solutions",
    location: "Delhi, India"
  },
  {
    email: "vivaan.patil@email.com",
    name: "Vivaan Patil",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Patil AgriTech",
    industry: "Agriculture",
    experience: "6 years in agricultural technology",
    bio: "Agri-tech entrepreneur modernizing farming practices",
    location: "Nashik, Maharashtra"
  },
  {
    email: "anika.shah@email.com",
    name: "Anika Shah",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Shah E-commerce",
    industry: "E-commerce",
    experience: "4 years in digital marketing",
    bio: "E-commerce specialist building marketplace solutions",
    location: "Mumbai, Maharashtra"
  },
  {
    email: "aditya.mishra@email.com",
    name: "Aditya Mishra",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Mishra EduTech",
    industry: "Education",
    experience: "8 years in education",
    bio: "Education technologist creating learning platforms",
    location: "Hyderabad, Telangana"
  },
  {
    email: "pari.gupta@email.com",
    name: "Pari Gupta",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Gupta Energy",
    industry: "Energy",
    experience: "5 years in renewable energy",
    bio: "Clean energy entrepreneur developing solar solutions",
    location: "Jaipur, Rajasthan"
  },
  {
    email: "reyansh.agarwal@email.com",
    name: "Reyansh Agarwal",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Agarwal Foods",
    industry: "Food & Beverage",
    experience: "6 years in food technology",
    bio: "Food tech innovator creating healthy alternatives",
    location: "Ahmedabad, Gujarat"
  },
  {
    email: "ira.pandey@email.com",
    name: "Ira Pandey",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Pandey Logistics",
    industry: "Logistics",
    experience: "4 years in supply chain",
    bio: "Logistics optimizer building tracking solutions",
    location: "Pune, Maharashtra"
  },
  {
    email: "vihaan.chowdhury@email.com",
    name: "Vihaan Chowdhury",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Chowdhury Real Estate",
    industry: "Real Estate",
    experience: "7 years in property technology",
    bio: "Prop-tech entrepreneur digitizing real estate",
    location: "Kolkata, West Bengal"
  },
  {
    email: "aarohi.sinha@email.com",
    name: "Aarohi Sinha",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Sinha Travel",
    industry: "Travel",
    experience: "5 years in travel industry",
    bio: "Travel tech founder creating booking platforms",
    location: "Goa, India"
  },
  {
    email: "atharv.chakraborty@email.com",
    name: "Atharv Chakraborty",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Chakraborty Entertainment",
    industry: "Entertainment",
    experience: "6 years in media production",
    bio: "Media entrepreneur developing content platforms",
    location: "Mumbai, Maharashtra"
  },
  {
    email: "myra.thakur@email.com",
    name: "Myra Thakur",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Thakur Automotive",
    industry: "Automotive",
    experience: "4 years in automotive design",
    bio: "Automotive designer creating electric vehicles",
    location: "Chennai, Tamil Nadu"
  },
  {
    email: "advik.yadav@email.com",
    name: "Advik Yadav",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Yadav Fashion",
    industry: "Fashion",
    experience: "5 years in fashion design",
    bio: "Fashion designer building sustainable clothing",
    location: "Delhi, India"
  },
  {
    email: "kavya.nair@email.com",
    name: "Kavya Nair",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Nair Sports",
    industry: "Sports",
    experience: "3 years in sports technology",
    bio: "Sports tech innovator creating training apps",
    location: "Kochi, Kerala"
  },
  {
    email: "ishaan.pillai@email.com",
    name: "Ishaan Pillai",
    userType: "creator" as const,
    isVerified: true,
    companyName: "Pillai Telecom",
    industry: "Telecommunications",
    experience: "6 years in telecom engineering",
    bio: "Telecom engineer developing communication tools",
    location: "Bangalore, Karnataka"
  }
];

export const sampleBusinessIdeas = [
  {
    title: "AI-Powered Personal Finance Assistant",
    description: "An intelligent mobile app that uses machine learning to provide personalized financial advice, budgeting tools, and investment recommendations tailored to individual financial goals and risk tolerance. Features include automated expense tracking, smart savings suggestions, and predictive financial planning.",
    category: "Technology",
    tags: ["AI", "Fintech", "Mobile App", "Personal Finance", "Machine Learning"],
    fundingGoal: 500000,
    currentFunding: 0,
    equityOffered: 15,
    valuation: 3000000,
    stage: "mvp" as const,
    timeline: "12 months to launch, 24 months to profitability",
    teamSize: 5
  },
  {
    title: "Sustainable Urban Farming Solutions",
    description: "Vertical farming technology for urban environments, enabling restaurants and households to grow fresh produce year-round using 90% less water and space than traditional farming. Our IoT-enabled systems automatically monitor and adjust growing conditions for optimal yield.",
    category: "Agriculture",
    tags: ["Sustainability", "Urban Farming", "AgriTech", "IoT", "Green Technology"],
    fundingGoal: 750000,
    currentFunding: 150000,
    equityOffered: 20,
    stage: "early" as const,
    timeline: "6 months to market expansion",
    teamSize: 8
  },
  {
    title: "Telemedicine Platform for Mental Health",
    description: "A comprehensive telemedicine platform specifically designed for mental health services, connecting patients with licensed therapists and providing evidence-based digital therapeutics. Includes secure video sessions, mood tracking, and AI-powered treatment recommendations.",
    category: "Healthcare",
    tags: ["Telemedicine", "Mental Health", "Healthcare", "Digital Health", "AI"],
    fundingGoal: 1000000,
    currentFunding: 300000,
    equityOffered: 12,
    valuation: 8000000,
    stage: "growth" as const,
    timeline: "Already profitable, expanding to new markets",
    teamSize: 15
  },
  {
    title: "Smart Inventory Management for Retail",
    description: "AI-powered inventory management system that uses computer vision and predictive analytics to optimize stock levels, reduce waste, and improve supply chain efficiency for retail businesses. Integrates with existing POS systems and provides real-time insights.",
    category: "Technology",
    tags: ["AI", "Retail", "Inventory Management", "Computer Vision", "Analytics"],
    fundingGoal: 600000,
    currentFunding: 0,
    equityOffered: 18,
    valuation: 3200000,
    stage: "concept" as const,
    timeline: "18 months to market ready",
    teamSize: 6
  },
  {
    title: "Electric Vehicle Battery Swap Network",
    description: "Network of automated battery swapping stations for electric vehicles, enabling drivers to swap depleted batteries for charged ones in under 2 minutes. Our standardized battery design works across multiple vehicle brands and includes a battery-as-a-service model.",
    category: "Automotive",
    tags: ["Electric Vehicles", "Battery Technology", "Clean Energy", "IoT", "SaaS"],
    fundingGoal: 2000000,
    currentFunding: 500000,
    equityOffered: 25,
    valuation: 7500000,
    stage: "early" as const,
    timeline: "12 months to first pilot station",
    teamSize: 12
  },
  {
    title: "Personalized Learning Platform for Schools",
    description: "Adaptive learning platform that uses AI to create personalized curricula for K-12 students based on their learning style, pace, and interests. Includes teacher dashboards, parent portals, and comprehensive progress tracking with detailed analytics.",
    category: "Education",
    tags: ["EdTech", "AI", "Personalized Learning", "Analytics", "Mobile App"],
    fundingGoal: 800000,
    currentFunding: 200000,
    equityOffered: 16,
    valuation: 4800000,
    stage: "mvp" as const,
    timeline: "8 months to full platform launch",
    teamSize: 9
  },
  {
    title: "Community Solar Power Sharing Platform",
    description: "Platform that enables communities to collectively invest in and share solar power generation. Users can buy shares in local solar installations and receive credits on their electricity bills. Includes blockchain-based energy tracking and trading.",
    category: "Energy",
    tags: ["Solar Energy", "Community", "Blockchain", "Sustainability", "Clean Energy"],
    fundingGoal: 450000,
    currentFunding: 0,
    equityOffered: 14,
    valuation: 3000000,
    stage: "concept" as const,
    timeline: "15 months to pilot community",
    teamSize: 7
  },
  {
    title: "Food Waste Reduction Marketplace",
    description: "Mobile marketplace connecting restaurants, grocery stores, and food manufacturers with consumers and food banks to redistribute surplus food before it expires. Uses AI to predict surplus and optimize distribution logistics.",
    category: "Food & Beverage",
    tags: ["Food Waste", "Sustainability", "Marketplace", "Mobile App", "AI"],
    fundingGoal: 350000,
    currentFunding: 75000,
    equityOffered: 17,
    valuation: 2000000,
    stage: "mvp" as const,
    timeline: "6 months to city-wide expansion",
    teamSize: 5
  },
  {
    title: "AR-Based Interior Design Assistant",
    description: "Augmented reality app that allows users to visualize furniture and decor in their space before purchasing. Partners with furniture retailers and includes social features for sharing designs. Uses computer vision for accurate room scanning.",
    category: "E-commerce",
    tags: ["AR", "Interior Design", "E-commerce", "Computer Vision", "Social"],
    fundingGoal: 650000,
    currentFunding: 150000,
    equityOffered: 19,
    valuation: 3200000,
    stage: "early" as const,
    timeline: "9 months to retailer partnerships",
    teamSize: 8
  },
  {
    title: "Remote Work Productivity Analytics",
    description: "Comprehensive platform for measuring and improving remote team productivity. Tracks engagement, collaboration patterns, and work-life balance while providing actionable insights for managers and personalized recommendations for employees.",
    category: "Technology",
    tags: ["Remote Work", "Productivity", "Analytics", "HR Tech", "SaaS"],
    fundingGoal: 550000,
    currentFunding: 0,
    equityOffered: 15,
    valuation: 3500000,
    stage: "concept" as const,
    timeline: "12 months to beta launch",
    teamSize: 6
  },
  {
    title: "Micro-Insurance Platform for Gig Workers",
    description: "Digital insurance platform offering affordable, customizable micro-insurance products for gig economy workers. Covers income protection, health emergencies, and equipment damage with flexible, usage-based premiums.",
    category: "Finance",
    tags: ["Insurance", "Gig Economy", "Fintech", "Micro-Insurance", "Digital"],
    fundingGoal: 900000,
    currentFunding: 250000,
    equityOffered: 13,
    valuation: 6500000,
    stage: "growth" as const,
    timeline: "Expanding to new gig platforms",
    teamSize: 11
  },
  {
    title: "Smart Traffic Management System",
    description: "IoT-based traffic management system using AI and real-time data to optimize traffic flow in urban areas. Reduces congestion, improves emergency response times, and integrates with smart city infrastructure.",
    category: "Technology",
    tags: ["IoT", "Smart City", "AI", "Traffic Management", "Urban Planning"],
    fundingGoal: 1200000,
    currentFunding: 300000,
    equityOffered: 22,
    valuation: 5000000,
    stage: "early" as const,
    timeline: "8 months to pilot intersection",
    teamSize: 10
  },
  {
    title: "Personalized Nutrition Planning App",
    description: "AI-powered nutrition app that creates personalized meal plans based on individual health goals, dietary restrictions, and genetic factors. Includes grocery integration, recipe suggestions, and progress tracking with healthcare provider connectivity.",
    category: "Healthcare",
    tags: ["Nutrition", "AI", "Mobile App", "Healthcare", "Personalized Medicine"],
    fundingGoal: 400000,
    currentFunding: 100000,
    equityOffered: 16,
    valuation: 2400000,
    stage: "mvp" as const,
    timeline: "6 months to healthcare partnerships",
    teamSize: 7
  },
  {
    title: "Sustainable Fashion Marketplace",
    description: "Online marketplace exclusively for sustainable and ethical fashion brands. Features include supply chain transparency, carbon footprint tracking, and a rental/subscription model for reducing fashion waste.",
    category: "Fashion",
    tags: ["Sustainable Fashion", "Marketplace", "E-commerce", "Sustainability", "Ethical"],
    fundingGoal: 300000,
    currentFunding: 50000,
    equityOffered: 18,
    valuation: 1600000,
    stage: "concept" as const,
    timeline: "10 months to brand partnerships",
    teamSize: 4
  },
  {
    title: "Drone-Based Delivery for Rural Areas",
    description: "Drone delivery service specifically designed for rural and remote areas with limited infrastructure. Delivers essential goods, medical supplies, and e-commerce packages using long-range, weather-resistant drones with AI-powered route optimization.",
    category: "Logistics",
    tags: ["Drone Technology", "Rural Delivery", "Logistics", "AI", "E-commerce"],
    fundingGoal: 1500000,
    currentFunding: 400000,
    equityOffered: 20,
    valuation: 7000000,
    stage: "early" as const,
    timeline: "12 months to commercial operations",
    teamSize: 14
  },
  {
    title: "Blockchain-Based Supply Chain Transparency",
    description: "End-to-end supply chain transparency platform using blockchain technology to track products from origin to consumer. Provides immutable records, prevents counterfeiting, and enables fair trade practices for farmers and artisans.",
    category: "Technology",
    tags: ["Blockchain", "Supply Chain", "Transparency", "Traceability", "Fair Trade"],
    fundingGoal: 850000,
    currentFunding: 200000,
    equityOffered: 14,
    valuation: 5800000,
    stage: "mvp" as const,
    timeline: "10 months to enterprise pilots",
    teamSize: 8
  },
  {
    title: "Virtual Reality Fitness Training",
    description: "Immersive VR fitness platform that makes workouts engaging and fun through gamification and virtual environments. Includes personalized training programs, social challenges, and progress tracking with real-time feedback.",
    category: "Sports",
    tags: ["VR", "Fitness", "Gamification", "Health Tech", "Social"],
    fundingGoal: 700000,
    currentFunding: 150000,
    equityOffered: 16,
    valuation: 4200000,
    stage: "early" as const,
    timeline: "8 months to app store launch",
    teamSize: 9
  },
  {
    title: "Smart Home Energy Management System",
    description: "AI-powered home energy management system that optimizes electricity usage, predicts consumption patterns, and integrates with renewable energy sources. Reduces energy bills by up to 30% while maintaining comfort levels.",
    category: "Energy",
    tags: ["Smart Home", "Energy Management", "AI", "IoT", "Sustainability"],
    fundingGoal: 950000,
    currentFunding: 300000,
    equityOffered: 18,
    valuation: 5000000,
    stage: "mvp" as const,
    timeline: "6 months to smart home integration",
    teamSize: 11
  },
  {
    title: "Digital Art Marketplace and NFT Platform",
    description: "Comprehensive marketplace for digital artists featuring NFT creation tools, secondary market trading, and social features. Includes artist verification, royalty tracking, and educational resources for new creators.",
    category: "Entertainment",
    tags: ["NFT", "Digital Art", "Marketplace", "Blockchain", "Social"],
    fundingGoal: 600000,
    currentFunding: 100000,
    equityOffered: 15,
    valuation: 3800000,
    stage: "concept" as const,
    timeline: "12 months to platform launch",
    teamSize: 7
  },
  {
    title: "Telecom Infrastructure Sharing Platform",
    description: "Platform that enables telecom companies to share infrastructure like towers and fiber networks, reducing costs and improving coverage. Uses AI to optimize resource allocation and predict network demands.",
    category: "Telecommunications",
    tags: ["Telecom", "Infrastructure", "Sharing Economy", "AI", "Network Optimization"],
    fundingGoal: 1800000,
    currentFunding: 500000,
    equityOffered: 22,
    valuation: 7800000,
    stage: "early" as const,
    timeline: "9 months to pilot network",
    teamSize: 13
  },
  {
    title: "Organic Waste-to-Energy Conversion",
    description: "Technology that converts organic waste into biogas and fertilizer using advanced anaerobic digestion. Creates revenue streams from waste management while producing clean energy for local communities.",
    category: "Energy",
    tags: ["Waste Management", "Biogas", "Clean Energy", "Sustainability", "Circular Economy"],
    fundingGoal: 1200000,
    currentFunding: 350000,
    equityOffered: 20,
    valuation: 5800000,
    stage: "mvp" as const,
    timeline: "8 months to commercial plant",
    teamSize: 10
  },
  {
    title: "AI-Powered Language Learning Platform",
    description: "Adaptive language learning platform using AI to personalize lessons based on learning style, progress, and goals. Features speech recognition, cultural context, and immersive conversation practice.",
    category: "Education",
    tags: ["AI", "Language Learning", "EdTech", "Personalization", "Mobile App"],
    fundingGoal: 750000,
    currentFunding: 200000,
    equityOffered: 17,
    valuation: 4200000,
    stage: "early" as const,
    timeline: "7 months to multi-language support",
    teamSize: 8
  },
  {
    title: "Autonomous Delivery Robots for Cities",
    description: "Fleet of autonomous ground robots for last-mile delivery in urban areas. Uses computer vision, AI path planning, and IoT sensors to navigate safely and efficiently deliver packages and food orders.",
    category: "Logistics",
    tags: ["Autonomous Robots", "Delivery", "AI", "Computer Vision", "Urban Mobility"],
    fundingGoal: 2200000,
    currentFunding: 600000,
    equityOffered: 25,
    valuation: 8500000,
    stage: "mvp" as const,
    timeline: "10 months to city deployment",
    teamSize: 16
  },
  {
    title: "Plant-Based Protein Alternative Products",
    description: "Development and production of plant-based protein products that match the taste and texture of traditional meat. Uses fermentation technology and novel ingredients to create sustainable, nutritious alternatives.",
    category: "Food & Beverage",
    tags: ["Plant-Based", "Protein", "Sustainability", "Food Tech", "Fermentation"],
    fundingGoal: 1300000,
    currentFunding: 400000,
    equityOffered: 19,
    valuation: 6500000,
    stage: "early" as const,
    timeline: "12 months to product launch",
    teamSize: 12
  },
  {
    title: "Construction Technology and Prefab Solutions",
    description: "Modular construction technology using prefabricated components and 3D printing for faster, cheaper, and more sustainable building. Reduces construction time by 60% and waste by 80%.",
    category: "Manufacturing",
    tags: ["Construction Tech", "3D Printing", "Prefabrication", "Sustainability", "Modular"],
    fundingGoal: 1900000,
    currentFunding: 550000,
    equityOffered: 23,
    valuation: 8000000,
    stage: "mvp" as const,
    timeline: "9 months to pilot construction",
    teamSize: 15
  },
  {
    title: "Mental Health Support Chatbot Platform",
    description: "AI-powered chatbot platform providing mental health support, crisis intervention, and therapy referrals. Uses natural language processing and evidence-based therapeutic techniques to supplement professional care.",
    category: "Healthcare",
    tags: ["Mental Health", "AI", "Chatbot", "NLP", "Digital Health"],
    fundingGoal: 800000,
    currentFunding: 250000,
    equityOffered: 16,
    valuation: 4800000,
    stage: "early" as const,
    timeline: "6 months to clinical trials",
    teamSize: 9
  },
  {
    title: "Carbon Credit Trading Marketplace",
    description: "Blockchain-based marketplace for trading carbon credits, connecting businesses with carbon reduction projects. Provides transparency, verification, and easy access to carbon offset opportunities.",
    category: "Finance",
    tags: ["Carbon Credits", "Blockchain", "Sustainability", "Marketplace", "Climate"],
    fundingGoal: 1100000,
    currentFunding: 300000,
    equityOffered: 18,
    valuation: 5800000,
    stage: "concept" as const,
    timeline: "14 months to regulatory approval",
    teamSize: 8
  },
  {
    title: "Autonomous Farming Equipment",
    description: "AI-powered autonomous tractors and farming equipment that can operate 24/7 with precision agriculture capabilities. Reduces labor costs, improves yield prediction, and optimizes resource usage.",
    category: "Agriculture",
    tags: ["Autonomous Vehicles", "AI", "Precision Agriculture", "AgriTech", "IoT"],
    fundingGoal: 2500000,
    currentFunding: 700000,
    equityOffered: 28,
    valuation: 8500000,
    stage: "mvp" as const,
    timeline: "12 months to field testing",
    teamSize: 18
  },
  {
    title: "Elderly Care Monitoring System",
    description: "IoT-based monitoring system for elderly care that tracks vital signs, detects falls, and provides medication reminders. Integrates with healthcare providers and family members for comprehensive care management.",
    category: "Healthcare",
    tags: ["Elderly Care", "IoT", "Health Monitoring", "Digital Health", "Safety"],
    fundingGoal: 650000,
    currentFunding: 180000,
    equityOffered: 15,
    valuation: 4100000,
    stage: "mvp" as const,
    timeline: "8 months to care home pilots",
    teamSize: 7
  }
];

export const sampleInvestmentOffers = [
  {
    title: "Tech Startup Investment Fund",
    description: "Looking to invest in early-stage technology companies with strong growth potential. We focus on B2B SaaS, AI/ML, and fintech startups with proven market traction and scalable business models.",
    amountRange: { min: 100000, max: 500000 },
    preferredEquity: { min: 10, max: 25 },
    preferredStages: ["mvp", "early", "growth"],
    preferredIndustries: ["Technology", "SaaS", "AI", "Fintech"],
    investmentType: "equity" as const,
    timeline: "3-5 year investment horizon"
  },
  {
    title: "Healthcare Innovation Fund",
    description: "Seeking innovative healthcare solutions and medical technology startups. We prioritize companies addressing unmet medical needs, improving patient outcomes, and reducing healthcare costs through technology.",
    amountRange: { min: 150000, max: 1000000 },
    preferredEquity: { min: 15, max: 30 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Healthcare", "Biotech", "Medical Devices", "Digital Health"],
    investmentType: "equity" as const,
    timeline: "5-7 year investment horizon"
  },
  {
    title: "Sustainable Energy Investment",
    description: "Investing in clean energy solutions and sustainable technology companies. We focus on renewable energy, energy storage, smart grid technologies, and companies reducing carbon footprint.",
    amountRange: { min: 200000, max: 1500000 },
    preferredEquity: { min: 10, max: 20 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Clean Energy", "Sustainability", "Environmental", "Energy Storage"],
    investmentType: "convertible" as const,
    timeline: "7-10 year investment horizon"
  },
  {
    title: "E-commerce and Retail Innovation",
    description: "Investing in innovative e-commerce and retail technology solutions. We seek companies improving online shopping experience, supply chain efficiency, and customer engagement through technology.",
    amountRange: { min: 75000, max: 400000 },
    preferredEquity: { min: 12, max: 22 },
    preferredStages: ["mvp", "early"],
    preferredIndustries: ["E-commerce", "Retail", "Consumer Goods", "Marketplace"],
    investmentType: "equity" as const,
    timeline: "3-5 year investment horizon"
  },
  {
    title: "Agri-Tech and Food Security Fund",
    description: "Supporting agricultural technology and food security innovations. We invest in companies improving farming efficiency, reducing food waste, and creating sustainable food supply chains.",
    amountRange: { min: 50000, max: 300000 },
    preferredEquity: { min: 8, max: 18 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Agriculture", "Food & Beverage", "Sustainability", "AgriTech"],
    investmentType: "equity" as const,
    timeline: "5-8 year investment horizon"
  },
  {
    title: "Education Technology Fund",
    description: "Investing in innovative education technology solutions. We focus on companies improving learning outcomes, expanding access to education, and creating engaging learning experiences.",
    amountRange: { min: 100000, max: 600000 },
    preferredEquity: { min: 14, max: 28 },
    preferredStages: ["mvp", "early", "growth"],
    preferredIndustries: ["Education", "EdTech", "Learning", "Training"],
    investmentType: "convertible" as const,
    timeline: "4-6 year investment horizon"
  },
  {
    title: "Mobility and Transportation Innovation",
    description: "Supporting next-generation mobility and transportation solutions. We invest in electric vehicles, autonomous technology, shared mobility, and smart transportation infrastructure.",
    amountRange: { min: 250000, max: 2000000 },
    preferredEquity: { min: 18, max: 35 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Automotive", "Electric Vehicles", "Transportation", "Mobility"],
    investmentType: "equity" as const,
    timeline: "6-8 year investment horizon"
  },
  {
    title: "Financial Services Innovation",
    description: "Investing in fintech and financial services innovation. We seek companies improving financial inclusion, payment systems, lending platforms, and personal finance management.",
    amountRange: { min: 125000, max: 800000 },
    preferredEquity: { min: 12, max: 24 },
    preferredStages: ["mvp", "early"],
    preferredIndustries: ["Finance", "Fintech", "Payments", "Banking"],
    investmentType: "equity" as const,
    timeline: "3-5 year investment horizon"
  },
  {
    title: "Real Estate Technology Fund",
    description: "Supporting property technology and real estate innovation. We invest in companies digitizing real estate transactions, property management, construction technology, and smart buildings.",
    amountRange: { min: 175000, max: 1200000 },
    preferredEquity: { min: 16, max: 30 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Real Estate", "Construction", "Property Management", "Smart Buildings"],
    investmentType: "convertible" as const,
    timeline: "5-7 year investment horizon"
  },
  {
    title: "Consumer Technology and Lifestyle",
    description: "Investing in consumer-facing technology and lifestyle brands. We focus on companies creating better consumer experiences through technology, design, and innovation.",
    amountRange: { min: 80000, max: 450000 },
    preferredEquity: { min: 10, max: 20 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Consumer Goods", "Lifestyle", "Fashion", "Entertainment"],
    investmentType: "equity" as const,
    timeline: "3-6 year investment horizon"
  },
  {
    title: "Manufacturing and Industrial Tech Fund",
    description: "Supporting advanced manufacturing technologies and industrial automation solutions. We invest in robotics, 3D printing, predictive maintenance, and smart factory technologies.",
    amountRange: { min: 300000, max: 1800000 },
    preferredEquity: { min: 15, max: 25 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Manufacturing", "Industrial Tech", "Robotics", "Automation"],
    investmentType: "equity" as const,
    timeline: "5-8 year investment horizon"
  },
  {
    title: "Sports Technology and Wellness Fund",
    description: "Investing in sports technology, fitness, and wellness innovations. We focus on wearable tech, performance analytics, training platforms, and preventive health solutions.",
    amountRange: { min: 125000, max: 750000 },
    preferredEquity: { min: 12, max: 22 },
    preferredStages: ["mvp", "early", "growth"],
    preferredIndustries: ["Sports", "Fitness", "Wellness", "Wearable Tech"],
    investmentType: "convertible" as const,
    timeline: "4-7 year investment horizon"
  },
  {
    title: "Media and Content Creation Fund",
    description: "Supporting digital media, content creation tools, and entertainment technology. We invest in streaming platforms, content management systems, and creator economy solutions.",
    amountRange: { min: 150000, max: 900000 },
    preferredEquity: { min: 14, max: 26 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Media", "Entertainment", "Content Creation", "Streaming"],
    investmentType: "equity" as const,
    timeline: "4-6 year investment horizon"
  },
  {
    title: "Retail Technology Innovation Fund",
    description: "Investing in retail technology solutions including point-of-sale systems, inventory management, customer experience, and omnichannel retail platforms.",
    amountRange: { min: 100000, max: 600000 },
    preferredEquity: { min: 13, max: 24 },
    preferredStages: ["mvp", "early"],
    preferredIndustries: ["Retail", "E-commerce", "Customer Experience", "POS Systems"],
    investmentType: "equity" as const,
    timeline: "3-6 year investment horizon"
  },
  {
    title: "Environmental Technology Fund",
    description: "Supporting clean technology and environmental solutions. We invest in water purification, air quality, waste management, and pollution control technologies.",
    amountRange: { min: 175000, max: 1200000 },
    preferredEquity: { min: 16, max: 28 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Clean Tech", "Environmental", "Water Tech", "Air Quality"],
    investmentType: "convertible" as const,
    timeline: "6-9 year investment horizon"
  },
  {
    title: "Consulting and Professional Services Tech",
    description: "Investing in technology solutions for consulting firms and professional services. We focus on practice management, client portals, and workflow automation tools.",
    amountRange: { min: 90000, max: 550000 },
    preferredEquity: { min: 11, max: 21 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Consulting", "Professional Services", "Practice Management", "Workflow"],
    investmentType: "equity" as const,
    timeline: "3-5 year investment horizon"
  },
  {
    title: "Travel and Hospitality Technology Fund",
    description: "Supporting travel technology and hospitality innovations. We invest in booking platforms, guest experience, operational efficiency, and sustainable tourism solutions.",
    amountRange: { min: 140000, max: 850000 },
    preferredEquity: { min: 15, max: 25 },
    preferredStages: ["mvp", "early", "growth"],
    preferredIndustries: ["Travel", "Hospitality", "Tourism", "Guest Experience"],
    investmentType: "equity" as const,
    timeline: "4-7 year investment horizon"
  },
  {
    title: "Fashion and Textile Innovation Fund",
    description: "Investing in fashion technology, sustainable textiles, and supply chain innovations. We focus on circular fashion, smart textiles, and manufacturing efficiency.",
    amountRange: { min: 85000, max: 500000 },
    preferredEquity: { min: 12, max: 23 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Fashion", "Textiles", "Sustainable Fashion", "Manufacturing"],
    investmentType: "equity" as const,
    timeline: "4-6 year investment horizon"
  },
  {
    title: "Government and Public Sector Tech Fund",
    description: "Supporting technology solutions for government and public sector organizations. We invest in civic tech, digital governance, and public service delivery platforms.",
    amountRange: { min: 200000, max: 1500000 },
    preferredEquity: { min: 18, max: 32 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Government Tech", "Civic Tech", "Public Sector", "Digital Governance"],
    investmentType: "convertible" as const,
    timeline: "5-8 year investment horizon"
  },
  {
    title: "Insurance Technology Innovation Fund",
    description: "Investing in insurance technology and risk management solutions. We focus on parametric insurance, usage-based policies, and automated claims processing.",
    amountRange: { min: 160000, max: 950000 },
    preferredEquity: { min: 14, max: 26 },
    preferredStages: ["mvp", "early"],
    preferredIndustries: ["Insurance", "Risk Management", "Parametric Insurance", "Claims Processing"],
    investmentType: "equity" as const,
    timeline: "4-7 year investment horizon"
  },
  {
    title: "Legal Technology and Document Management",
    description: "Supporting legal technology solutions and document management platforms. We invest in contract automation, legal research tools, and practice management software.",
    amountRange: { min: 110000, max: 700000 },
    preferredEquity: { min: 13, max: 24 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Legal Tech", "Document Management", "Contract Automation", "Legal Research"],
    investmentType: "equity" as const,
    timeline: "3-6 year investment horizon"
  },
  {
    title: "Aerospace and Defense Technology Fund",
    description: "Investing in aerospace technology, defense innovations, and space-related startups. We focus on drone technology, satellite systems, and advanced materials.",
    amountRange: { min: 500000, max: 3000000 },
    preferredEquity: { min: 20, max: 40 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Aerospace", "Defense", "Drones", "Satellite Technology"],
    investmentType: "equity" as const,
    timeline: "7-10 year investment horizon"
  },
  {
    title: "Non-Profit and Social Impact Tech Fund",
    description: "Supporting technology solutions for non-profit organizations and social impact initiatives. We invest in donor management, volunteer coordination, and impact measurement tools.",
    amountRange: { min: 75000, max: 400000 },
    preferredEquity: { min: 10, max: 20 },
    preferredStages: ["concept", "mvp"],
    preferredIndustries: ["Non-Profit Tech", "Social Impact", "Donor Management", "Impact Measurement"],
    investmentType: "convertible" as const,
    timeline: "4-6 year investment horizon"
  },
  {
    title: "Real Estate Investment Technology Fund",
    description: "Investing in real estate technology, proptech, and property management solutions. We focus on rental platforms, property valuation, and construction management tools.",
    amountRange: { min: 225000, max: 1400000 },
    preferredEquity: { min: 17, max: 30 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Real Estate", "PropTech", "Property Management", "Construction"],
    investmentType: "equity" as const,
    timeline: "5-8 year investment horizon"
  },
  {
    title: "Maritime and Shipping Technology Fund",
    description: "Supporting maritime technology, shipping logistics, and port management solutions. We invest in vessel tracking, route optimization, and supply chain visibility tools.",
    amountRange: { min: 180000, max: 1100000 },
    preferredEquity: { min: 16, max: 28 },
    preferredStages: ["mvp", "early"],
    preferredIndustries: ["Maritime", "Shipping", "Logistics", "Port Management"],
    investmentType: "equity" as const,
    timeline: "5-7 year investment horizon"
  },
  {
    title: "Veterinary and Animal Health Tech Fund",
    description: "Investing in veterinary technology and animal health innovations. We focus on telemedicine for pets, animal monitoring devices, and veterinary practice management.",
    amountRange: { min: 95000, max: 550000 },
    preferredEquity: { min: 12, max: 22 },
    preferredStages: ["concept", "mvp", "early"],
    preferredIndustries: ["Veterinary", "Animal Health", "Pet Tech", "Telemedicine"],
    investmentType: "equity" as const,
    timeline: "3-6 year investment horizon"
  },
  {
    title: "Event Management and Ticketing Platform Fund",
    description: "Supporting event technology and ticketing platform innovations. We invest in event management software, virtual events, and attendee engagement solutions.",
    amountRange: { min: 135000, max: 800000 },
    preferredEquity: { min: 14, max: 25 },
    preferredStages: ["mvp", "early", "growth"],
    preferredIndustries: ["Event Tech", "Ticketing", "Event Management", "Virtual Events"],
    investmentType: "convertible" as const,
    timeline: "4-7 year investment horizon"
  },
  {
    title: "Gaming and Interactive Entertainment Fund",
    description: "Investing in gaming technology, esports, and interactive entertainment solutions. We focus on game development tools, esports platforms, and immersive gaming experiences.",
    amountRange: { min: 175000, max: 1000000 },
    preferredEquity: { min: 15, max: 27 },
    preferredStages: ["early", "growth"],
    preferredIndustries: ["Gaming", "Esports", "Interactive Entertainment", "Game Development"],
    investmentType: "equity" as const,
    timeline: "4-7 year investment horizon"
  },
  {
    title: "Human Resources Technology Fund",
    description: "Supporting HR technology and talent management solutions. We invest in recruitment platforms, employee engagement tools, and performance management systems.",
    amountRange: { min: 120000, max: 750000 },
    preferredEquity: { min: 13, max: 24 },
    preferredStages: ["mvp", "early"],
    preferredIndustries: ["HR Tech", "Recruitment", "Talent Management", "Employee Engagement"],
    investmentType: "equity" as const,
    timeline: "3-6 year investment horizon"
  }
];

// Helper function to generate random timestamps within the last 30 days
export function getRandomTimestamp(daysAgo: number = 30): number {
  const now = Date.now();
  const randomDays = Math.floor(Math.random() * daysAgo) * 24 * 60 * 60 * 1000;
  return now - randomDays;
}

// Helper function to generate current funding amounts
export function getRandomCurrentFunding(goal: number, maxPercentage: number = 0.6): number {
  const maxFunding = Math.floor(goal * maxPercentage);
  return Math.floor(Math.random() * maxFunding);
}

// Sample matches data
export const sampleMatches = [
  {
    ideaId: "", // Will be filled with actual idea IDs during seeding
    investorId: "", // Will be filled with actual investor IDs during seeding
    creatorId: "", // Will be filled with actual creator IDs during seeding
    offerId: "", // Will be filled with actual offer IDs during seeding
    matchScore: 0.85,
    matchingFactors: {
      amountCompatibility: 0.9,
      industryAlignment: 0.95,
      stagePreference: 0.8,
      riskAlignment: 0.75,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.78,
    matchingFactors: {
      amountCompatibility: 0.85,
      industryAlignment: 0.9,
      stagePreference: 0.7,
      riskAlignment: 0.7,
    },
    status: "viewed" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.92,
    matchingFactors: {
      amountCompatibility: 0.95,
      industryAlignment: 0.98,
      stagePreference: 0.85,
      riskAlignment: 0.9,
    },
    status: "contacted" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.67,
    matchingFactors: {
      amountCompatibility: 0.7,
      industryAlignment: 0.8,
      stagePreference: 0.6,
      riskAlignment: 0.6,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.88,
    matchingFactors: {
      amountCompatibility: 0.9,
      industryAlignment: 0.95,
      stagePreference: 0.8,
      riskAlignment: 0.85,
    },
    status: "negotiating" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.73,
    matchingFactors: {
      amountCompatibility: 0.8,
      industryAlignment: 0.85,
      stagePreference: 0.65,
      riskAlignment: 0.7,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.81,
    matchingFactors: {
      amountCompatibility: 0.85,
      industryAlignment: 0.9,
      stagePreference: 0.75,
      riskAlignment: 0.75,
    },
    status: "viewed" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.95,
    matchingFactors: {
      amountCompatibility: 0.98,
      industryAlignment: 1.0,
      stagePreference: 0.9,
      riskAlignment: 0.9,
    },
    status: "invested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.69,
    matchingFactors: {
      amountCompatibility: 0.75,
      industryAlignment: 0.8,
      stagePreference: 0.6,
      riskAlignment: 0.65,
    },
    status: "rejected" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.84,
    matchingFactors: {
      amountCompatibility: 0.9,
      industryAlignment: 0.95,
      stagePreference: 0.75,
      riskAlignment: 0.8,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.76,
    matchingFactors: {
      amountCompatibility: 0.8,
      industryAlignment: 0.85,
      stagePreference: 0.7,
      riskAlignment: 0.7,
    },
    status: "contacted" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.89,
    matchingFactors: {
      amountCompatibility: 0.95,
      industryAlignment: 0.9,
      stagePreference: 0.85,
      riskAlignment: 0.85,
    },
    status: "negotiating" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.71,
    matchingFactors: {
      amountCompatibility: 0.75,
      industryAlignment: 0.8,
      stagePreference: 0.65,
      riskAlignment: 0.7,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.82,
    matchingFactors: {
      amountCompatibility: 0.85,
      industryAlignment: 0.9,
      stagePreference: 0.75,
      riskAlignment: 0.8,
    },
    status: "viewed" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.93,
    matchingFactors: {
      amountCompatibility: 0.95,
      industryAlignment: 0.98,
      stagePreference: 0.9,
      riskAlignment: 0.9,
    },
    status: "invested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.65,
    matchingFactors: {
      amountCompatibility: 0.7,
      industryAlignment: 0.75,
      stagePreference: 0.6,
      riskAlignment: 0.6,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.87,
    matchingFactors: {
      amountCompatibility: 0.9,
      industryAlignment: 0.95,
      stagePreference: 0.8,
      riskAlignment: 0.85,
    },
    status: "contacted" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.79,
    matchingFactors: {
      amountCompatibility: 0.85,
      industryAlignment: 0.9,
      stagePreference: 0.7,
      riskAlignment: 0.75,
    },
    status: "negotiating" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.74,
    matchingFactors: {
      amountCompatibility: 0.8,
      industryAlignment: 0.85,
      stagePreference: 0.65,
      riskAlignment: 0.7,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.91,
    matchingFactors: {
      amountCompatibility: 0.95,
      industryAlignment: 0.95,
      stagePreference: 0.85,
      riskAlignment: 0.9,
    },
    status: "viewed" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.68,
    matchingFactors: {
      amountCompatibility: 0.75,
      industryAlignment: 0.8,
      stagePreference: 0.6,
      riskAlignment: 0.65,
    },
    status: "rejected" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.86,
    matchingFactors: {
      amountCompatibility: 0.9,
      industryAlignment: 0.95,
      stagePreference: 0.8,
      riskAlignment: 0.8,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.77,
    matchingFactors: {
      amountCompatibility: 0.8,
      industryAlignment: 0.85,
      stagePreference: 0.7,
      riskAlignment: 0.75,
    },
    status: "contacted" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.94,
    matchingFactors: {
      amountCompatibility: 0.98,
      industryAlignment: 1.0,
      stagePreference: 0.9,
      riskAlignment: 0.9,
    },
    status: "invested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.72,
    matchingFactors: {
      amountCompatibility: 0.75,
      industryAlignment: 0.8,
      stagePreference: 0.65,
      riskAlignment: 0.7,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.83,
    matchingFactors: {
      amountCompatibility: 0.85,
      industryAlignment: 0.9,
      stagePreference: 0.75,
      riskAlignment: 0.8,
    },
    status: "viewed" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.75,
    matchingFactors: {
      amountCompatibility: 0.8,
      industryAlignment: 0.85,
      stagePreference: 0.65,
      riskAlignment: 0.7,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.88,
    matchingFactors: {
      amountCompatibility: 0.9,
      industryAlignment: 0.95,
      stagePreference: 0.8,
      riskAlignment: 0.85,
    },
    status: "negotiating" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.66,
    matchingFactors: {
      amountCompatibility: 0.7,
      industryAlignment: 0.75,
      stagePreference: 0.6,
      riskAlignment: 0.6,
    },
    status: "suggested" as const,
  },
  {
    ideaId: "",
    investorId: "",
    creatorId: "",
    offerId: "",
    matchScore: 0.90,
    matchingFactors: {
      amountCompatibility: 0.95,
      industryAlignment: 0.95,
      stagePreference: 0.85,
      riskAlignment: 0.85,
    },
    status: "contacted" as const,
  }
];